module.exports = {
    PORT_REQ_REP_ATAHUALPA_CLIENT_REQUEST_WORKER : 5555,
    PORT_REQ_REP_ATAHUALPA_CLIENT_MESSAGES:6666,
    PORT_PUB_SUB_ATAHUALPA_CHASKI_MESSAGES : 7777,
    PORT_PUB_SUB_ATAHUALPA_CHASKI_OPS : 9999,
    PORT_PUB_SUB_CHASKI_CLIENT_PINGS: 8888,
    LOG_LEVEL_DEBUG : 20,
    LOG_LEVEL_WARN : 40,
    LOG_LEVEL_ERROR : 50,
    CHASKI_TYPE_ZEROMQ: "ZEROMQ",
    CHASKI_TYPE_SOCKETIO: "SOCKETIO"
};
